### PR TITLE
Add missing package 'react-animated-css'

### PR DESCRIPTION
**Pull request by rag594**

### CODE REVIEW

**Comment by shakdwipeea** [comment]
@rag594 Does this automatically bundle css files also ? Right now, I see that the cdn link is being
used directly here. https://github.com/entranceplus/UI-Repo/blob/master/public/index.html#L23

**Comment by rag594** [comment]
No, while building this error came up, I don't think it is even using that css file.https://github.com/entranceplus/UI-Repo/blob/01c09c55d3fcc2a193dc6c56e604082ea8d24025/src/components/Login.jsx#L3

**Comment by arjita-mitra** [comment]
Thanks for pointing out. I have added the library in package.json. Take a
pull and run npm install now you shouldn't get any build error.

Regards
Arjita

**Comment by rag594** [comment]
Fixed in a7d9bf4dd51c3ee7d60b46b5510c1f73a8444a3e

**Pull request closed without merging**
